// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vFgfC09BAgtn4fpTRNQOrzyr9TURPFI',
    appId: '1:244263586271:web:325b8026d819fe07505c6a',
    messagingSenderId: '244263586271',
    projectId: 'flutter-meetup-vicenza-demo',
    authDomain: 'flutter-meetup-vicenza-demo.firebaseapp.com',
    storageBucket: 'flutter-meetup-vicenza-demo.appspot.com',
    measurementId: 'G-8QF1C4TJ1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCROQ2TWFba0F3UbthkWoPAx_CrAROOONc',
    appId: '1:244263586271:android:454fdf8667ef14ba505c6a',
    messagingSenderId: '244263586271',
    projectId: 'flutter-meetup-vicenza-demo',
    storageBucket: 'flutter-meetup-vicenza-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrDBhflT9Xd2bBY3NXodQDVwvGWjImPE',
    appId: '1:244263586271:ios:e6609e72c20f1ad0505c6a',
    messagingSenderId: '244263586271',
    projectId: 'flutter-meetup-vicenza-demo',
    storageBucket: 'flutter-meetup-vicenza-demo.appspot.com',
    iosClientId: '244263586271-ssnvhf83dq5eenob5fb3re0d3q8tavsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocDemo',
  );
}
